### ISSUE TITLE
LineCircleCollision does not work when given vectors.

### ISSUE THREAD

**Issue by mau-fyi** [bmoren/p5.collide#52]

**Comment by bmoren** [comment]
can you provide an example?

**Comment by bmoren** [comment]
are you using

`collideLineCircleVector()`
or
`collideLineCircle( )`

**Comment by mau-fyi** [comment]
In my project the line `collideLineCircle(a, b, c, r)` won't work but, `collideLineCircle(a.x, a.y, b.x, b.y, c.x, c.y, r)` does work.

Here is some example code
```javascript
function setup() {
  createCanvas(400, 400);
}

function draw() {
  let a = createVector(200,300);
  let b = createVector(100,150);
  let c = createVector(mouseX,mouseY);
  
  background(255);
  line(a.x, a.y, b.x, b.y);
  circle(c.x, c.y, 50);
  
  
  hit = collideLineCircle(a, b, c, 50);
  // hit = collideLineCircle(a.x, a.y, b.x, b.y, c.x, c.y, 50);

  stroke(hit ? color('red') : 0);
  // print('colliding?', hit);
}
```

**Comment by mau-fyi** [comment]
Sorry, just now realized that the commented-out line using vectors in the documentation is referring to an entirely different method.
